-- RA2: Schema de base de datos para proyecto JDBC educativo
-- Base de datos H2 (compatible con PostgreSQL mode)
-- Estudiantes deben usar JDBC puro para interactuar con estas tablas

-- Eliminar tablas si existen (para poder recrear en cada arranque)
DROP TABLE IF EXISTS user_statistics CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Tabla principal: users
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    department VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para mejorar rendimiento de consultas
CREATE INDEX idx_users_department ON users(department);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_active ON users(active);
CREATE INDEX idx_users_email ON users(email);

-- Tabla para estadísticas agregadas (opcional - para JOINs avanzados)
CREATE TABLE user_statistics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    login_count INTEGER DEFAULT 0,
    last_login TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Nota sobre Triggers:
-- H2 soporta triggers pero con sintaxis Java. Para este proyecto educativo,
-- los estudiantes actualizarán updated_at manualmente en sus métodos UPDATE.
-- En PostgreSQL, se usaría un trigger automático.

-- Nota sobre Stored Procedures:
-- H2 soporta funciones Java que se pueden llamar como stored procedures.
-- Los estudiantes aprenderán a usar CallableStatement con queries directas
-- o funciones Java registradas con CREATE ALIAS.
-- Ver: src/test/resources/README_stored_procedures.md para más detalles
